"""Add password and mail

Revision ID: 38d0769b1be6
Revises: 42e3ee348574
Create Date: 2023-06-27 02:18:37.890080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d0769b1be6'
down_revision = '42e3ee348574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint(None, ['mail'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('mail')

    # ### end Alembic commands ###
